# Generated by Django 2.2.5 on 2019-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nombre_mesa',
            field=models.CharField(default='Hola', max_length=40),
        ),
    ]
