# Generated by Django 2.2.5 on 2019-10-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidos_nombre_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='nombre_mesa',
        ),
    ]
