# Generated by Django 2.2.5 on 2019-10-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedidos_nombre_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='orden',
            field=models.TextField(default='Orden:', max_length=200),
        ),
    ]
