# Generated by Django 2.2.5 on 2019-10-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pedidos.Mesa'),
        ),
    ]
