# Generated by Django 2.2.5 on 2019-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20191011_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='mesa',
            field=models.IntegerField(),
        ),
    ]
